Disable LTO for ESP8266 due to build errors
These require investigation:
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: libc_replacements.cpp.o (symbol from plugin): in function `_open_r':
(.text+0x0): multiple definition of `puts'; /home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-puts.o):/workdir/repo/newlib/newlib/libc/stdio/puts.c:129: first defined here
/home/runner/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_wiring_digital.cpp:129:3: warning: type 'struct ArgStructure' violates the C++ One Definition Rule [-Wodr]
  129 | } ArgStructure;
      |   ^
/home/runner/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/FunctionalInterrupt.h:26:8: note: a different type is defined in another translation unit
   26 | struct ArgStructure {
      |        ^
/home/runner/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_wiring_digital.cpp:128:8: note: the first difference of corresponding definitions is field 'functionInfo'
  128 |  void* functionInfo;
      |        ^
/home/runner/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/FunctionalInterrupt.h:28:16: note: a field of same name but different type is defined in another translation unit
   28 |  FunctionInfo* functionInfo = nullptr;
      |                ^
/home/runner/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_wiring_digital.cpp:129:3: note: type 'void' should match type 'struct FunctionInfo'
  129 | } ArgStructure;
      |   ^
/home/runner/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/FunctionalInterrupt.h:21:8: note: the incompatible type is defined here
   21 | struct FunctionInfo {
      |        ^
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/firmware.elf section `.text1' will not fit in region `iram1_0_seg'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o:(.text+0x4): undefined reference to `stack_thunk_save'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o:(.text+0x8): undefined reference to `SigningVerifier_verify'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o: in function `thunk_SigningVerifier_verify':
<artificial>:(.text+0x1f): undefined reference to `SigningVerifier_verify'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: <artificial>:(.text+0x32): undefined reference to `stack_thunk_fatal_smashing'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: <artificial>:(.text+0x72): undefined reference to `stack_thunk_fatal_smashing'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o: in function `thunk_br_ssl_engine_recvapp_ack':
<artificial>:(.text+0xb2): undefined reference to `stack_thunk_fatal_smashing'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o: in function `thunk_br_ssl_engine_recvapp_buf':
<artificial>:(.text+0xf2): undefined reference to `stack_thunk_fatal_smashing'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o: in function `thunk_br_ssl_engine_recvrec_ack':
<artificial>:(.text+0x132): undefined reference to `stack_thunk_fatal_smashing'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o:<artificial>:(.text+0x172): more undefined references to `stack_thunk_fatal_smashing' follow
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans0.ltrans.o: in function `__wrap_system_restart_local':
<artificial>:(.text.__wrap_system_restart_local+0x2): undefined reference to `postmortem_report'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /tmp/firmware.elf.ojg0kn.ltrans3.ltrans.o: in function `_ZN8Espalexa18handleAlexaApiCallEP21AsyncWebServerRequest':
<artificial>:(.text+0x3c68): undefined reference to `_ZN23NeoEsp8266I2sMethodCore15c_StateDataSizeE'
collect2: error: ld returned 1 exit status
*** [.pio/build/nodemcuv2/firmware.elf] Error 1

Signed-off-by: Alastair D'Silva <alastair@d-silva.org>