back to NeoPixelBus @ 2.7.1
due to build errors on some esp32 envs.

Build Environments (esp32_16MB_M_eth)
In file included from wled00/bus_manager.cpp:9:0:
wled00/bus_wrapper.h: In static member function 'static void PolyBus::begin(void*, uint8_t, uint8_t*)':
wled00/bus_wrapper.h:187:61: error: 'DotStarEsp32DmaHspi5MhzMethod' was not declared in this scope
 #define B_HS_DOT_3 NeoPixelBrightnessBus<DotStarBgrFeature, DotStarEsp32DmaHspi5MhzMethod> //hardware HSPI with DMA (ESP32 only)
                                                             ^
wled00/bus_wrapper.h:300:37: note: in expansion of macro 'B_HS_DOT_3'
       case I_HS_DOT_3: (static_cast<B_HS_DOT_3*>(busPtr))->Begin(pins[1], -1, pins[0], -1); break;
                                     ^
wled00/bus_wrapper.h:187:90: error: template argument 2 is invalid
 #define B_HS_DOT_3 NeoPixelBrightnessBus<DotStarBgrFeature, DotStarEsp32DmaHspi5MhzMethod> //hardware HSPI with DMA (ESP32 only)
                                                                                          In file included from wled00/bus_manager.cpp:9:0:
wled00/bus_wrapper.h: In static member function 'static void PolyBus::begin(void*, uint8_t, uint8_t*)':
wled00/bus_wrapper.h:187:61: error: 'DotStarEsp32DmaHspi5MhzMethod' was not declared in this scope
 #define B_HS_DOT_3 NeoPixelBrightnessBus<DotStarBgrFeature, DotStarEsp32DmaHspi5MhzMethod> //hardware HSPI with DMA (ESP32 only)
                                                             ^
wled00/bus_wrapper.h:300:37: note: in expansion of macro 'B_HS_DOT_3'
       case I_HS_DOT_3: (static_cast<B_HS_DOT_3*>(busPtr))->Begin(pins[1], -1, pins[0], -1); break;
                                     ^
wled00/bus_wrapper.h:187:90: error: template argument 2 is invalid
 #define B_HS_DOT_3 NeoPixelBrightnessBus<DotStarBgrFeature, DotStarEsp32DmaHspi5MhzMethod> //hardware HSPI with DMA (ESP32 only)